### ISSUE TITLE
Yewtu.be not remembering settings upon browser close reopen

### ISSUE THREAD

**Issue by PrincessMiki** [unixfox/invidious-custom#42] opened 2022-07-17 06:54 UTC
This is happening both on Android and Ubuntu

**Comment by unixfox** [comment] 2022-07-17 07:58
Maybe you have an extension that clear the cookies? Idk it works fine on my end.

You should try on other browsers.

**Comment by PrincessMiki** [comment] 2022-07-17 08:01
> Maybe you have an extension that clear the cookies? Idk it works fine on my end.
> 
> You should try on other browsers.

Did you miss the part where I said that I tried on Android and Ubuntu? 😛 It was working fine  up until like 2 weeks ago ish

**Comment by PrincessMiki** [comment] 2022-07-17 08:03
I don't have any extensions on Android

**Comment by unixfox** [comment] 2022-07-17 08:39
Can you reproduce the same issue on other invidious instances: https://instances.invidious.io?

**Comment by PrincessMiki** [comment] 2022-07-17 08:40
Doesn't happen on other instances, at least the 2 others I tried

**Comment by PrincessMiki** [comment] 2022-07-17 08:41
Specifically it's not remembering the medium quality setting. He keeps on going back to the default setting of HD

**Comment by PrincessMiki** [comment] 2022-07-22 16:31
Update, if i refresh the vid page it retrieves the correct settings

**Comment by unixfox** [comment] 2022-07-22 19:47
Please post the videos ID that you tried.

I tried to replicate the issue and I couldn't replicate your issue.

**Comment by PrincessMiki** [comment] 2022-07-24 08:36
Found this: Invidious is acting weirdly that it doesn't accept settings if it got redirected from youtube.com, this issue is the same as this. It also happens with embeds. The happened recently as invidious changed a little bit

**Comment by PrincessMiki** [comment] 2022-07-24 08:38
> Please post the videos ID that you tried.
> 
> I tried to replicate the issue and I couldn't replicate your issue.

https://yewtu.be/watch?v=k4v6slOxxXs&list=PLChiKQUYPsJ9_ZXHeT287Ry2tIX1AiSkq&index=20

https://yewtu.be/watch?v=WZM9uq-KKhk

**Comment by unixfox** [comment] 2022-07-24 08:56
Are you sure your issue is not the same as this one: https://github.com/iv-org/invidious/issues/3132?

**Comment by PrincessMiki** [comment] 2022-08-02 00:33
> Are you sure your issue is not the same as this one: [iv-org/invidious#3132](https://github.com/iv-org/invidious/issues/3132)?

It sounds similar, but i've never logged in

**Comment by unixfox** [comment] 2022-08-06 17:13
Closing because it's a general invidious issue: https://github.com/iv-org/invidious/issues/3132

**Closed by unixfox** 2022-08-06 17:13 UTC
